[build]
  base = "gkchatty-local"
  command = "cd frontend && pnpm install && pnpm build"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_API_BASE_URL = "https://staging-gk-chatty.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"
