[build]
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "https://staging-gk-chatty.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Credentials = "true"
